# Generated by Django 4.2.6 on 2023-10-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Spartito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("spartito_image", models.ImageField(upload_to="spartiti/")),
                (
                    "musicxml_file",
                    models.FileField(blank=True, null=True, upload_to="musicxml/"),
                ),
            ],
        ),
    ]
